#created by: alexsandro/dejavudf - github.com/dejavudf
#type: template
---
- name: Script Enable Access Rule
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    #- ./vars/default_vars.yml
    #- ./credentials/gaia_credentials.yml

  tasks:

    - name: Login SESSION
      uri:
        url: "http://192.168.15.4/login/Auth"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded; charset=UTF-8"
        body:
          username: "admin"
          password: "password"
        body_format: json
        return_content: yes
        validate_certs: False


      register: login_output

    # - debug:
    #     var: login_output

    - name: Get Info Page
      uri:
        url: "http://192.168.15.4/img/main-logo.png"
        method: GET   
        body_format: json
        status_code: 200
        return_content: yes
        validate_certs: False
      register: result

    - name: Print Info
      debug:
        var: result

    - name: Logout Session
      uri:
        url: "http://192.168.15.4/goform/exit"
        method: GET
        body_format: json
        status_code: 200
        return_content: yes
        validate_certs: False
